# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pbauthor < Formula
  desc ""
  homepage ""
  version "0.0.10"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pathbird/pbauthor/releases/download/v0.0.10/pbauthor_0.0.10_macos_amd64.tar.gz"
      sha256 "2ea5373b3bbb9157a857e28c4fc9ef24fdc6ab95c16cac39a71a1ff5991d7573"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pathbird/pbauthor/releases/download/v0.0.10/pbauthor_0.0.10_linux_amd64.tar.gz"
      sha256 "e39a596da7ce5e0acfbe64fb6bf5a9cb52f765a04b0e698456e96211b9ab1ac4"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pathbird/pbauthor/releases/download/v0.0.10/pbauthor_0.0.10_linux_arm64.tar.gz"
      sha256 "6db11dd3e8656ab2869ae65d518ef4a18465d84df24930413fd65dceda9001c5"
    end
  end

  def install
    bin.install "pbauthor"
  end
end
